version: '2'

services:
   #app:
   #   image: esame-attsw-bellocci
   #   depends_on:
   #      - mysql_db
   #   networks:
   #      - esame-network
   
   mysql_db:
      image: mysql:8
      container_name: mysql
      #restart: always
      command: --default-authentication-plugin=mysql_native_password
      #networks:
      #   - esame-network
      ports:
         - "3307:3306"
      environment:
         MYSQL_ROOT_PASSWORD: "root"
         MYSQL_DATABASE: "library"
         MYSQL_USER: "user"
         MYSQL_PASSWORD: "password"
      volumes:
         - db_data:/var/lib/mysql
         
   adminer_container:
      image: adminer:4
      environment:
         ADMINER_DEFAULT_SERVER: mysql_db_container
      ports:
         - "8080:8080"
  
volumes:
  db_data: {}

#networks:
#   esame-network:
#      driver: bridge